// AInvest MCP v2 原型使用的事实清单。
// current* 字段描述 2026-08-31 实测现状；target* 字段只描述建议方案。

const OFFICIAL_API_OPERATION_FACTS = [
  {
    id: "getAnalystRatingsConsensus",
    group: "分析师评级",
    method: "GET",
    path: "/analysis-ratings/consensus",
    name: "评级共识与目标价",
    currentMcp: "full",
    currentTool: "get-analyst-ratings",
    status: "verified",
    targetTool: "get_analyst_ratings",
    note: "REST 与 MCP 入参一致。",
  },
  {
    id: "getAnalystRatingsHistory",
    group: "分析师评级",
    method: "GET",
    path: "/analysis-ratings/history",
    name: "历史评级",
    currentMcp: "full",
    currentTool: "get-analyst-ratings-history",
    status: "verified",
    targetTool: "get_analyst_ratings",
    note: "现有 MCP 额外支持按机构过滤。",
  },
  {
    id: "getEarningsCalendar",
    group: "日历",
    method: "GET",
    path: "/calendar/earnings",
    name: "财报日历",
    currentMcp: "full",
    currentTool: "get-calendar-earnings",
    status: "verified",
    targetTool: "get_calendar_events",
    note: "已直接映射。",
  },
  {
    id: "getEarningsBacktestingResults",
    group: "日历",
    method: "GET",
    path: "/calendar/earnings/backtesting",
    name: "财报回测",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_calendar_events",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getDividendsCalendar",
    group: "日历",
    method: "GET",
    path: "/calendar/dividends",
    name: "分红日历",
    currentMcp: "full",
    currentTool: "get-calendar-dividends",
    status: "verified",
    targetTool: "get_calendar_events",
    note: "已直接映射。",
  },
  {
    id: "getIPOCalendar",
    group: "日历",
    method: "GET",
    path: "/calendar/ipo",
    name: "IPO 日历",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_calendar_events",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getCorporateActionsCalendar",
    group: "日历",
    method: "GET",
    path: "/calendar/corporateactions",
    name: "公司行动日历",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_calendar_events",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getEconomicEventsCalendar",
    group: "日历",
    method: "GET",
    path: "/calendar/economics",
    name: "经济事件日历",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_calendar_events",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getCandles",
    group: "市场数据",
    method: "GET",
    path: "/marketdata/candles",
    name: "OHLCV K 线",
    currentMcp: "partial",
    currentTool: "get-marketdata-candles",
    status: "verified",
    targetTool: "get_bars",
    note: "MCP 缺 session、adjustment；且把可默认的 to 改成必填。",
  },
  {
    id: "getTrades",
    group: "市场数据",
    method: "GET",
    path: "/marketdata/trades",
    name: "逐笔成交",
    currentMcp: "full",
    currentTool: "get-marketdata-trades",
    status: "verified",
    targetTool: "get_trades",
    note: "当前仅支持当日成交，能力边界应写入工具描述。",
  },
  {
    id: "getLatestNewsWires",
    group: "新闻",
    method: "GET",
    path: "/news/v1/wire/page/history",
    name: "快讯列表",
    currentMcp: "partial",
    currentTool: "get-news-headlines",
    status: "verified",
    targetTool: "get_news",
    note: "MCP 缺 tab、start_id，且行业枚举被硬编码。",
  },
  {
    id: "getNewsContent",
    group: "新闻",
    method: "GET",
    path: "/news/v1/wire/info/{content_id}",
    name: "快讯正文",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_news_content",
    note: "2025-10 起使用 content_id；当前 MCP 未提供。",
  },
  {
    id: "getLatestArticles",
    group: "新闻",
    method: "GET",
    path: "/news/v1/article/page/history",
    name: "文章列表",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_news",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getArticleContent",
    group: "新闻",
    method: "GET",
    path: "/news/v1/article/info/{content_id}",
    name: "文章正文",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_news_content",
    note: "2025-10 起使用 content_id；当前 MCP 未提供。",
  },
  {
    id: "getInsiderTrades",
    group: "持仓与交易",
    method: "GET",
    path: "/ownership/insider",
    name: "内部人交易",
    currentMcp: "partial",
    currentTool: "get-ownership-insider",
    status: "verified",
    targetTool: "get_ownership",
    note: "MCP 未保留 page、size 的默认值与最小值约束。",
  },
  {
    id: "getCongressTrades",
    group: "持仓与交易",
    method: "GET",
    path: "/ownership/congress",
    name: "国会议员交易",
    currentMcp: "partial",
    currentTool: "get-ownership-congress",
    status: "verified",
    targetTool: "get_ownership",
    note: "MCP 未保留 page、size 的默认值与最小值约束。",
  },
  {
    id: "searchSecurities",
    group: "证券",
    method: "GET",
    path: "/securities/search",
    name: "证券搜索",
    currentMcp: "full",
    currentTool: "securities-search",
    status: "verified",
    targetTool: "resolve_instrument",
    note: "已直接映射；v2 与内部 market_code 解析合并。",
  },
  {
    id: "getStockProfile",
    group: "证券",
    method: "GET",
    path: "/securities/stock/profile",
    name: "股票资料",
    currentMcp: "missing",
    currentTool: null,
    status: "route_drift",
    targetTool: "get_instrument_profile",
    note: "OpenAPI YAML 已声明且标记 MCP enabled，但文档导航缺页。",
  },
  {
    id: "getStockFinancials",
    group: "证券",
    method: "GET",
    path: "/securities/stock/financials",
    name: "股票财务指标",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_financials",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getStockEarnings",
    group: "证券",
    method: "GET",
    path: "/securities/stock/financials/earnings",
    name: "个股财报",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_financials",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getStockDividends",
    group: "证券",
    method: "GET",
    path: "/securities/stock/financials/dividends",
    name: "个股分红",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_financials",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getStockFinancialStatements",
    group: "证券",
    method: "GET",
    path: "/securities/stock/financials/statements",
    name: "财务报表",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_financials",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
  {
    id: "getEtfHoldings",
    group: "证券",
    method: "GET",
    path: "/securities/etf/holdings",
    name: "ETF 持仓",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "list_relations",
    note: "可与内部 holding 关系能力归一。",
  },
  {
    id: "getEtfProfile",
    group: "证券",
    method: "GET",
    path: "/securities/etf/profile",
    name: "ETF 资料",
    currentMcp: "missing",
    currentTool: null,
    status: "verified",
    targetTool: "get_instrument_profile",
    note: "官方 REST 已有，当前 MCP 未提供。",
  },
];

export const INTERNAL_ENDPOINTS = [
  {
    id: "indicatorSnapshot",
    family: "指标",
    method: "POST",
    path: "/index_api/indicator/v2/snapshot",
    name: "指标快照",
    currentStatus: "implemented",
    targetTool: "get_metric_snapshot",
    scope: "advanced_quote.read",
    note: "23 个受控场景模板；≤50 指标，分页每页≤1000。",
  },
  {
    id: "indicatorSeries",
    family: "指标",
    method: "POST",
    path: "/index_api/indicator/v2/series",
    name: "指标序列",
    currentStatus: "implemented",
    targetTool: "get_metric_series",
    scope: "advanced_quote.read",
    note: "4 个模板；≤16 标的、≤20 指标、每组合≤2000点。",
  },
  {
    id: "relationList",
    family: "关系",
    method: "POST",
    path: "/index_api/relation/v1/list",
    name: "关系列表",
    currentStatus: "implemented",
    targetTool: "list_relations",
    scope: "advanced_quote.read",
    note: "7 个模板；holding、component 等关系统一输出。",
  },
  {
    id: "multiKline",
    family: "行情",
    method: "POST",
    path: "/quote/v2/multi_kline",
    name: "多标的 K 线",
    currentStatus: "implemented",
    targetTool: "get_bars",
    scope: "marketdata.read",
    note: "≤16 标的、≤2000 bars。",
  },
  {
    id: "singleTick",
    family: "行情",
    method: "POST",
    path: "/quote/v2/single_tick",
    name: "单标的逐笔",
    currentStatus: "implemented",
    targetTool: "get_trades",
    scope: "marketdata.read",
    note: "一次只允许一个标的。",
  },
  {
    id: "lastSnapshot",
    family: "行情",
    method: "POST",
    path: "/quote/v2/last_snapshot",
    name: "最新交易日快照",
    currentStatus: "active_unwrapped",
    targetTool: "get_quotes",
    scope: "advanced_quote.read",
    note: "内部文档标为 active；运行稳定性、授权与契约尚未验证，现有 skill 执行器未包装。",
  },
  {
    id: "lastCalc",
    family: "行情",
    method: "POST",
    path: "/quote/v2/last_calc",
    name: "最新交易日计算项",
    currentStatus: "active_unwrapped",
    targetTool: "get_quotes",
    scope: "advanced_quote.read",
    note: "内部文档标为 active；运行稳定性、授权与契约尚未验证，现有 skill 执行器未包装。",
  },
  {
    id: "lastStats",
    family: "行情",
    method: "POST",
    path: "/quote/v2/last_stats",
    name: "区间统计",
    currentStatus: "active_unwrapped",
    targetTool: "get_quotes",
    scope: "advanced_quote.read",
    note: "内部文档标为 active；运行稳定性、授权与契约尚未验证，现有 skill 执行器未包装。",
  },
  {
    id: "realFundFlow",
    family: "资金流",
    method: "POST",
    path: "/quote/v2/real_fund_flow",
    name: "实时大单资金流",
    currentStatus: "active_unwrapped",
    targetTool: "get_fund_flow",
    scope: "advanced_quote.read",
    note: "内部文档标为 active；仅 UUS，运行稳定性、授权与契约尚未验证。",
  },
  {
    id: "singleKline",
    family: "行情",
    method: "POST",
    path: "/quote/v2/single_kline",
    name: "单标的 K 线",
    currentStatus: "active_unwrapped",
    targetTool: "get_bars",
    scope: "advanced_quote.read",
    note: "内部文档标为 active；运行稳定性、授权与契约尚未验证，可由统一 get_bars 适配。",
  },
  {
    id: "singleDaysKline",
    family: "行情",
    method: "POST",
    path: "/quote/v2/single_days_kline",
    name: "多日分钟 K 线",
    currentStatus: "active_unwrapped",
    targetTool: "get_bars",
    scope: "advanced_quote.read",
    note: "内部文档标为 active；运行稳定性、授权与契约尚未验证，现有 skill 执行器未包装。",
  },
  {
    id: "codeStatus",
    family: "标的",
    method: "POST",
    path: "/quote/v2/code_status",
    name: "代码状态",
    currentStatus: "active_unwrapped",
    targetTool: "get_instrument_profile",
    scope: "securities.read",
    note: "内部文档标为 active；运行稳定性、授权与契约尚未验证，现有 skill 执行器未包装。",
  },
  {
    id: "sort",
    family: "排行",
    method: "POST",
    path: "/quote/v2/sort",
    name: "行情排序",
    currentStatus: "active_unwrapped",
    targetTool: "rank_instruments",
    scope: "advanced_quote.read",
    note: "内部文档标为 active；运行、授权与契约待验证。最多返回 100 条，附加字段少于 20 个。",
  },
].map((endpoint) => ({
  ...endpoint,
  v2Migration: endpoint.currentStatus === "implemented" ? "b_side_mapped" : "blocked",
}));

export const UNAVAILABLE_INTERNAL_ENDPOINTS = [
  {
    id: "singleTrend",
    family: "行情",
    method: "POST",
    path: "/quote/v2/single_trend",
    name: "个股分时",
    currentStatus: "unavailable",
    targetTool: null,
    scope: null,
    note: "内部文档明确标注暂不提供；由分钟 K 线替代。",
  },
  {
    id: "tradeHours",
    family: "标的",
    method: "POST",
    path: "/quote/v2/trade_hours",
    name: "代码时间轴",
    currentStatus: "unavailable",
    targetTool: null,
    scope: null,
    note: "内部文档明确标注暂不支持。",
  },
  {
    id: "codeInfo",
    family: "标的",
    method: "POST",
    path: "/quote/v2/code_info",
    name: "代码基础信息",
    currentStatus: "unavailable",
    targetTool: null,
    scope: null,
    note: "内部文档已划除；不得包装成可用工具。",
  },
].map((endpoint) => ({ ...endpoint, v2Migration: "unavailable" }));

export const B_SIDE_ROUTES = [
  {
    id: "snapshot",
    method: "POST",
    path: "/index_api/indicator/v2/snapshot",
    keyRef: "index-api",
    tool: "get_metric_snapshot",
    family: "指标",
  },
  {
    id: "series",
    method: "POST",
    path: "/index_api/indicator/v2/series",
    keyRef: "index-api",
    tool: "get_metric_series",
    family: "指标",
  },
  {
    id: "relationList",
    method: "POST",
    path: "/index_api/relation/v1/list",
    keyRef: "index-api",
    tool: "list_relations",
    family: "关系",
  },
  {
    id: "multiKline",
    method: "POST",
    path: "/quote/v2/multi_kline",
    keyRef: "quoteag",
    tool: "get_bars",
    family: "行情",
  },
  {
    id: "singleTick",
    method: "POST",
    path: "/quote/v2/single_tick",
    keyRef: "quoteag",
    tool: "get_trades",
    family: "行情",
  },
];

export const B_SIDE_TRANSPORT = {
  gatewayLabel: "B 端 APISIX",
  authHeader: "apikey",
  programHeader: "X-Auth-ProgId",
  programId: "7080",
  contentType: "application/json",
  acceptLanguage: "en",
};

const OFFICIAL_TO_B_SIDE = {
  getCandles: "multiKline",
  getTrades: "singleTick",
  getEtfHoldings: "relationList",
};

export const OFFICIAL_API_OPERATIONS = OFFICIAL_API_OPERATION_FACTS.map((operation) => {
  const bSideRouteId = OFFICIAL_TO_B_SIDE[operation.id] ?? null;
  return {
    ...operation,
    bSideRouteId,
    v2Migration: bSideRouteId
      ? "b_side_mapped"
      : operation.currentMcp === "missing" ? "blocked" : "legacy_compat",
  };
});

export const KEY_METRICS = [
  {
    id: "officialOperations",
    value: "24",
    label: "官方 OpenAPI 操作",
    note: "23 个导航页 + 1 个 YAML 漂移路由",
    tone: "neutral",
  },
  {
    id: "currentCoverage",
    value: "41.7%",
    label: "当前 MCP 直接覆盖",
    note: "10 / 24；另有 1 个派生工具",
    tone: "warning",
  },
  {
    id: "bSideRoutes",
    value: "5",
    label: "二期 B 端直连路由",
    note: "index-api 3 条 + quoteag 2 条",
    tone: "info",
  },
  {
    id: "validatedScenarios",
    value: "36 / 36",
    label: "场景模板校验通过",
    note: "模板是服务端目录，不等于 36 个工具",
    tone: "success",
  },
  {
    id: "metricRows",
    value: "1,537",
    label: "本地指标元数据行",
    note: "2026-06-09 快照；上线前必须刷新",
    tone: "info",
  },
  {
    id: "internalActive",
    value: "13",
    label: "内部数据候选端点",
    note: "5 个已包装 + 8 个文档 active、待验证",
    tone: "warning",
  },
];

export const IMPROVEMENT_CARDS = [
  {
    id: "coverage",
    priority: "P0",
    title: "覆盖率只有 41.7%",
    current: "24 个官方操作仅 10 个被直接映射，14 个对 AI 不可见。",
    solution: "从 OpenAPI 自动生成 coverage manifest；任一新增/缺失操作让 CI 失败。",
    evidence: "官方规格 24；在线 MCP 11 tools，其中 1 个为派生工具。",
  },
  {
    id: "schemaDrift",
    priority: "P0",
    title: "工具契约不可机器校验",
    current: "11/11 无 outputSchema，且错误标为非幂等；K 线、新闻、持仓参数仍有漂移。",
    solution: "官方能力从 OpenAPI 生成，B 端能力从内部协议生成；所有只读查询统一标为幂等。",
    evidence: "在线 tools/list 与官方 YAML 的协议和字段逐项对比。",
  },
  {
    id: "internalGap",
    priority: "P0",
    title: "二期不能继续走一期上游",
    current: "一期经 docsmcp / OpenAPI 调用，继续复用会让二期受旧路由和旧契约约束。",
    solution: "Hosted MCP 直接接 B 端 APISIX：3 条 index-api、2 条 quoteag，按 family 取 key。",
    evidence: "quote skill 的 B 端路由、apikey 分组与 X-Auth-ProgId 规则。",
  },
  {
    id: "auth",
    priority: "P0",
    title: "鉴权和错误表达不一致",
    current: "仍靠手填 Bearer；无 OAuth discovery，未授权可能返回普通文本、空数组或 404。",
    solution: "外部使用 OAuth 2.1；内部 key 留在 secret store，index-api 与 quoteag 分开轮换审计。",
    evidence: "官方示例和未授权 tools/call 实测；两个 .well-known 地址均为 405。",
  },
  {
    id: "catalog",
    priority: "P1",
    title: "工具目录与文档会漂移",
    current: "聚合 openapi.json 返回 404；股票资料路由存在于 YAML，却不在导航中。",
    solution: "发布唯一版本化 catalog，自动生成文档、SDK、MCP schema 与 changelog。",
    evidence: "官方聚合规格 404；securities.yaml 与导航不一致。",
  },
  {
    id: "payload",
    priority: "P1",
    title: "返回结构和大结果不统一",
    current: "不同来源的分页、空值、时间和单位语义不一致，易挤占模型上下文。",
    solution: "统一 envelope、cursor、result budget、provenance；大结果以 resource URI 返回。",
    evidence: "内部模板与官方 REST 响应模型交叉检查。",
  },
  {
    id: "contentSafety",
    priority: "P1",
    title: "新闻路由已漂移，正文还有内容风险",
    current: "现网 headlines 请求错误路径并返回 404；未来正文还可能包含 HTML 或伪指令。",
    solution: "先修复 /history 路由；正文按不可信数据隔离，清洗 HTML 并保留来源与 as_of。",
    evidence: "线上 get-news-headlines 实测与官方 News YAML 对照。",
  },
];

export const ROADMAP = [
  {
    phase: "P0",
    title: "建立 B 端数据面",
    time: "0–4 周",
    goal: "先切断二期对一期执行链路的依赖。",
    deliverables: [
      "实现 B-side connector 与服务端 secret store",
      "3 条 index-api / 2 条 quoteag 固定路由",
      "统一注入 apikey 与 X-Auth-ProgId: 7080",
      "24 项能力标注 mapped / compat / blocked",
    ],
    acceptance: "5 / 5 路由契约通过；v2 trace 中没有一期 OpenAPI hop。",
  },
  {
    phase: "P1",
    title: "迁移并开放已封装能力",
    time: "5–8 周",
    goal: "让外部 AI 只带 OAuth，也能安全调用 B 端数据。",
    deliverables: [
      "5 个 quote skill endpoint 全部迁入 B 端 connector",
      "上线指标搜索、描述与版本状态",
      "统一分页、provenance、resource URI 与结果预算",
      "覆盖 ChatGPT、Claude、Cursor、VS Code、Codex 等接入指南",
    ],
    acceptance: "3 + 2 key 路由无串用；客户端配置中没有 B 端 host 或 key。",
  },
  {
    phase: "P2",
    title: "规模化与治理",
    time: "9–12 周",
    goal: "把目录、质量和成本治理变成持续系统。",
    deliverables: [
      "自动刷新指标目录并保留版本",
      "按租户限流、缓存、审计与成本归因",
      "旧 docsmcp 仅作兼容入口并发布弃用窗口",
      "为新闻内容增加持续安全评测",
    ],
    acceptance: "新 B 端路由逐项获批；文档、MCP 与指标目录无漂移，SLO 可观测。",
  },
];

export const SCOPES = [
  { id: "securities.read", label: "证券", includes: "搜索、资料、标的解析与状态" },
  { id: "calendar.read", label: "日历", includes: "财报、分红、IPO、宏观与公司行动" },
  { id: "marketdata.read", label: "市场数据", includes: "B 端 K 线与逐笔成交" },
  { id: "news.read", label: "新闻", includes: "快讯、文章与正文" },
  { id: "ownership.read", label: "持仓交易", includes: "内部人和国会议员交易" },
  { id: "ratings.read", label: "评级", includes: "评级共识、历史与机构" },
  { id: "advanced_quote.read", label: "高级行情", includes: "指标、关系、资金流、排序与内部行情" },
  { id: "catalog.read", label: "目录", includes: "API、指标、能力状态与版本" },
];

const SEMANTIC_TOOL_CANDIDATES = [
  {
    name: "resolve_instrument",
    domain: "标的",
    scope: "securities.read",
    summary: "按代码、中英文名或别名解析统一 market_code。",
    sources: ["local:marketcode"],
    priority: "core",
  },
  {
    name: "list_instruments",
    domain: "标的",
    scope: "securities.read",
    summary: "按资产类型、市场与分页枚举标的。",
    sources: ["local:marketcode"],
    priority: "core",
  },
  {
    name: "list_industries",
    domain: "标的",
    scope: "securities.read",
    summary: "查询 1–4 级行业目录；支持中英文名称。",
    sources: ["local:marketcode"],
    priority: "core",
  },
  {
    name: "list_industry_components",
    domain: "标的",
    scope: "securities.read",
    summary: "按行业层级返回成分标的并支持分页。",
    sources: ["local:marketcode"],
    priority: "core",
  },
  {
    name: "get_instrument_profile",
    domain: "证券",
    scope: "securities.read",
    summary: "统一返回股票或 ETF 基本资料与代码状态。",
    sources: ["contract:official", "candidate:internal"],
    priority: "core",
  },
  {
    name: "get_financials",
    domain: "证券",
    scope: "securities.read",
    summary: "按 kind 返回财务指标、报表、财报或分红。",
    sources: ["contract:official"],
    priority: "core",
  },
  {
    name: "get_calendar_events",
    domain: "日历",
    scope: "calendar.read",
    summary: "按 event_type 查询六类官方日历数据。",
    sources: ["contract:official"],
    priority: "core",
  },
  {
    name: "get_bars",
    domain: "行情",
    scope: "marketdata.read",
    summary: "通过 quoteag multi_kline 返回单/多标的 K 线，不回退一期 candles。",
    sources: ["b_side:quoteag"],
    priority: "core",
  },
  {
    name: "get_trades",
    domain: "行情",
    scope: "marketdata.read",
    summary: "通过 quoteag single_tick 返回单标的逐笔，并明确当日数据边界。",
    sources: ["b_side:quoteag"],
    priority: "core",
  },
  {
    name: "get_quotes",
    domain: "行情",
    scope: "advanced_quote.read",
    summary: "返回最新快照、计算项与区间统计。",
    sources: ["candidate:internal"],
    priority: "core",
  },
  {
    name: "get_fund_flow",
    domain: "行情",
    scope: "advanced_quote.read",
    summary: "返回经授权市场的盘中大中小单资金流；当前候选源仅 UUS。",
    sources: ["candidate:internal"],
    priority: "core",
  },
  {
    name: "rank_instruments",
    domain: "行情",
    scope: "advanced_quote.read",
    summary: "按受控字段排序标的；服务端执行条数、字段和时间范围上限。",
    sources: ["candidate:internal"],
    priority: "core",
  },
  {
    name: "get_news",
    domain: "新闻",
    scope: "news.read",
    summary: "按类型、标的、行业与游标检索快讯或文章。",
    sources: ["contract:official"],
    priority: "core",
  },
  {
    name: "get_news_content",
    domain: "新闻",
    scope: "news.read",
    summary: "按 content_id 获取经安全隔离的正文。",
    sources: ["contract:official"],
    priority: "core",
  },
  {
    name: "get_ownership",
    domain: "持仓交易",
    scope: "ownership.read",
    summary: "按 owner_type 查询内部人或国会议员交易。",
    sources: ["contract:official"],
    priority: "core",
  },
  {
    name: "get_analyst_ratings",
    domain: "评级",
    scope: "ratings.read",
    summary: "返回评级共识、历史或机构列表。",
    sources: ["contract:official", "candidate:derived"],
    priority: "core",
  },
  {
    name: "search_metrics",
    domain: "指标目录",
    scope: "catalog.read",
    summary: "搜索 1,279 个唯一指标及其适用端点。",
    sources: ["catalog"],
    priority: "core",
  },
  {
    name: "describe_metric",
    domain: "指标目录",
    scope: "catalog.read",
    summary: "返回指标单位、参数、支持端点与目录版本。",
    sources: ["catalog"],
    priority: "core",
  },
  {
    name: "get_metric_snapshot",
    domain: "指标",
    scope: "advanced_quote.read",
    summary: "执行受控指标快照查询，不暴露原始 body。",
    sources: ["b_side:index-api"],
    priority: "core",
  },
  {
    name: "get_metric_series",
    domain: "指标",
    scope: "advanced_quote.read",
    summary: "执行受控指标序列查询并限制结果点数。",
    sources: ["b_side:index-api"],
    priority: "core",
  },
  {
    name: "list_relations",
    domain: "关系",
    scope: "advanced_quote.read",
    summary: "通过 index-api relation_list 返回 ETF 持仓与各类成分关系。",
    sources: ["b_side:index-api"],
    priority: "core",
  },
  {
    name: "search_api_catalog",
    domain: "能力发现",
    scope: "catalog.read",
    summary: "按意图、分组、scope 搜索全部可用 operation。",
    sources: ["catalog"],
    priority: "discovery",
  },
  {
    name: "call_api_operation",
    domain: "能力发现",
    scope: "catalog.read + operation scope",
    summary: "只调用 b_side_mapped operation_id；兼容项与阻塞项不可执行，禁止任意 URL。",
    sources: ["b_side_registry"],
    priority: "discovery",
  },
];

const LOCAL_CATALOG_TOOL_NAMES = new Set([
  "resolve_instrument",
  "list_instruments",
  "list_industries",
  "list_industry_components",
  "search_metrics",
  "describe_metric",
  "search_api_catalog",
]);

export const SEMANTIC_TOOLS = SEMANTIC_TOOL_CANDIDATES.map((tool) => {
  const bSideRoute = B_SIDE_ROUTES.find((route) => route.tool === tool.name);
  if (bSideRoute) {
    return { ...tool, sources: [`b_side:${bSideRoute.keyRef}`], v2Availability: "b_side_mapped" };
  }
  if (LOCAL_CATALOG_TOOL_NAMES.has(tool.name)) {
    return { ...tool, v2Availability: "local_catalog" };
  }
  if (tool.name === "call_api_operation") {
    return { ...tool, sources: ["b_side_registry"], v2Availability: "b_side_router" };
  }
  return {
    ...tool,
    sources: tool.sources.map((source) => source === "official"
      ? "contract:official"
      : source === "internal" ? "candidate:internal" : source),
    v2Availability: "blocked",
  };
});
